# Generated by Django 4.1.5 on 2023-01-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='아이디어명')),
                ('content', models.TextField(verbose_name='아이디어설명')),
                ('interest', models.IntegerField(verbose_name='아이디어관심도')),
                ('devtool', models.CharField(max_length=50, verbose_name='예상개발툴')),
            ],
        ),
    ]
