# Generated by Django 4.1.5 on 2023-01-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_kind_post_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='개발툴설명')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='이름')),
                ('kind', models.CharField(max_length=50, null=True, verbose_name='종류')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
